### ISSUE TITLE
1.0.5 Values Appear to be Wrong

### ISSUE THREAD

**Issue by wcmille** [garycourt/korc#13]
It appears that the thrust numbers for parts like the Terrier are now too high (240+ vac thrust) instead of 60. These don't seem to match results from the game.

**Comment by garycourt** [comment]
Squad must have changed how these values are defined in the part files. Unfortunately I'm on vacation and can't fix this until next week.

**Comment by wcmille** [comment]
No worries. Love this app!

**Comment by garycourt** [comment]
Should be fixed now.
