### ISSUE TITLE
Optimization of time complexity

### ISSUE THREAD

**Issue by mferrie** [garycourt/korc#24]
Does this use a genetic algorithm? If not, how difficult would it be to implement one?

Based on the current code, it looks like you’re using a brute-force search, which, if I’m not mistaken, has been proven to be a massively inefficient (on the order of O(n!)) last-resort search...

**Comment by wcmille** [comment]
In practice, it's really not that bad. If n is the number of stages, there aren't many solutions where increasing the number of stages beyond 4 or 5 is useful.

I think what this is doing is looking at a set of possibilities, then continuing to add more possibilities to a FIFO queue as it runs. If you changed the FIFO queue to a priority queue, what scheme would you use? If you tried to cull some configurations without trying them, how would you do that?

**Comment by garycourt** [comment]
As @wcmille has pointed out, the random brute-force solution here is good enough, and finds a decent solution within a reasonable time frame.
