### ISSUE TITLE
Downloaded repo and tried to run it but I get a web worker error

### ISSUE THREAD

**Issue by WarpPrime** [garycourt/korc#26]
I downloaded the KORC repo and opened it as a local file. When I opened index.html I got a web worker error saying that my browser doesn't support it, when it works on github.io. Any solutions?

**Comment by garycourt** [comment]
You are probably trying to load the web page locally. Chrome doesn't let you load web workers when running scripts from a local file. Use a locally running webserver to host your local copy to get web workers working.
